[package]
name = "meeturbait-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.6"
actix-session = { version = "0.10.1", features = ["cookie-session"] }
actix-web = "4.9.0"
dotenvy = "0.15.7"
env_logger = "0.11.6"
log = "0.4.22"
serde = "1.0.217"
